
# ------------------------------------------------- the material-weakness roster
# Each year's roster as the report prints it, paired with a canonical key. The
# key is what makes persistence measurable: the Department renamed the systems
# weakness three times between FY2018 and FY2022 ("Financial Management Systems
# and Information Technology" -> "Legacy Systems" -> "Financial Management
# Systems Modernization") without the underlying condition changing, and a
# roster keyed on the printed label would report that as closures and new
# findings. The key is a judgement and is published as one; the printed label is
# always kept beside it so a reader can reject the pairing without distrusting
# the counts.
ROSTER = {
 2018: [('fin_systems_it','Financial Management Systems and Information Technology'),
        ('uot','Universe of Transactions'), ('compilation','Financial Statement Compilation'),
        ('fbwt','Fund Balance with Treasury'), ('ar','Accounts Receivable'),
        ('oms','Operating Material & Supplies'), ('inventory','Inventory and Related Property'),
        ('gpppe','General Property, Plant & Equipment'),
        ('gfp','Government Property in Possession of Contractors'),
        ('ap','Accounts Payable'), ('env','Environmental and Disposals Liabilities'),
        ('legal','Legal Contingencies'), ('begbal','Beginning Balances'),
        ('unsupported_adj','Journal Vouchers'), ('intragov','Intragovernmental Eliminations'),
        ('gross_costs','Statement of Net Costs'),
        ('recon_outlays','Reconciliation of Net Cost of Operations to Budget'),
        ('budgetary','Budgetary Resources'), ('elc','Entity Level Controls'),
        ('oversight_dod','Oversight and Monitoring')],
 2019: [('fin_systems_it','Financial Management Systems and Information Technology'),
        ('uot','Universe of Transactions'), ('fbwt','Fund Balance With Treasury'),
        ('suspense','Suspense Accounts'), ('inventory','Inventory and Related Property'),
        ('oms','Operating Materials & Supplies'), ('gpppe','General Property, Plant & Equipment'),
        ('realprop','Real Property'), ('gfp','Government Property in Possession of Contractors'),
        ('jsf','Joint Strike Fighter Program'), ('mhpi','Military Housing Privatization Initiative'),
        ('ap','Accounts Payable'), ('env','Environmental and Disposal Liabilities'),
        ('legal','Legal Contingencies'), ('begbal','Beginning Balances'),
        ('unsupported_adj','Unsupported Accounting Adjustments'),
        ('intragov','Intradepartmental Eliminations and Intragovernmental Transactions'),
        ('gross_costs','Gross Costs'), ('earned_rev','Earned Revenue'),
        ('recon_outlays','Reconciliation of Net Cost to Outlays'),
        ('budgetary','Budgetary Resources'), ('service_org','Service Providers'),
        ('elc','Entity-Level Controls'), ('oversight_dod','DoD-Wide Oversight and Monitoring'),
        ('oversight_comp','Component-Level Oversight and Monitoring')],
 2020: [('fin_systems_it','Legacy Systems'),
        ('config_security','Configuration Management and Security Management'),
        ('access','Access Controls'), ('sod','Segregation of Duties'),
        ('uot','Universe of Transactions'), ('fbwt','Fund Balance with Treasury'),
        ('suspense','Suspense Accounts'), ('inventory','Inventory and Related Property'),
        ('oms','Operating Material & Supplies'), ('gpppe','General Property, Plant & Equipment'),
        ('realprop','Real Property'), ('gfp','Government Property in Possession of Contractors'),
        ('jsf','Joint Strike Fighter Program'), ('mhpi','Military Housing Privatization Initiative'),
        ('ap','Accounts Payable'), ('env','Environmental and Disposal Liabilities'),
        ('begbal','Beginning Balances'), ('unsupported_adj','Unsupported Accounting Adjustments'),
        ('intragov','Intradepartmental Eliminations and Intragovernmental Transactions'),
        ('gross_costs','Gross Costs'), ('earned_rev','Earned Revenue'),
        ('budgetary','Budgetary Resources'), ('service_org','Service Providers'),
        ('elc','Entity-Level Controls'), ('oversight_dod','DoD-Wide Oversight and Monitoring'),
        ('oversight_comp','Component-Level Oversight and Monitoring')],
 2021: [('fin_systems_it','Legacy Systems'),
        ('config_security','Configuration Management and Security Management'),
        ('access','Access Controls'), ('sod','Segregation of Duties'),
        ('uot','Universe of Transactions'), ('compilation','Financial Statement Compilation'),
        ('fbwt','Fund Balance With Treasury'), ('suspense','Suspense Accounts'),
        ('inventory','Inventory and Stockpile Materials'),
        ('oms','Operating Materials and Supplies'),
        ('gpppe','General Property, Plant, and Equipment'), ('realprop','Real Property'),
        ('gfp','Government Property in the Possession of Contractors'),
        ('jsf','Joint Strike Fighter Program'), ('legal','Contingent Legal Liabilities'),
        ('ap','Accounts Payable'), ('env','Environmental and Disposal Liabilities'),
        ('begbal','Beginning Balances'), ('unsupported_adj','Unsupported Accounting Adjustments'),
        ('intragov','Intragovernmental Transactions and Intradepartmental Eliminations'),
        ('gross_costs','Gross Costs'), ('earned_rev','Earned Revenue'),
        ('recon_outlays','Reconciliation of Net Cost of Operations to Outlays'),
        ('budgetary','Budgetary Resources'), ('service_org','Service Organizations'),
        ('elc','Entity-Level Controls'), ('oversight_dod','DoD-Wide Oversight and Monitoring'),
        ('oversight_comp','Component-Level Oversight and Monitoring')],
 2022: [('fin_systems_it','Financial Management Systems Modernization'),
        ('config_security','Configuration Management and Security Management'),
        ('access','Access Controls'), ('sod','Segregation of Duties'),
        ('interface','Interface Controls'), ('uot','Universe of Transactions'),
        ('reporting_entity','Reporting Entity'), ('component_accounts','DoD Component-level Accounts'),
        ('fbwt','Fund Balance with Treasury'), ('inventory','Inventory and Stockpile Materials'),
        ('oms','Operating Materials and Supplies'),
        ('gpppe','General Property, Plant, and Equipment'), ('realprop','Real Property'),
        ('gfp','Government Property in the Possession of Contractors'),
        ('jsf','Joint Strike Fighter Program'), ('ap','Accounts Payable'),
        ('env','Environmental and Disposal Liabilities'), ('legal','Contingent Legal Liabilities'),
        ('begbal','Beginning Balances'), ('unsupported_adj','Unsupported Accounting Adjustments'),
        ('intragov','Intragovernmental Transactions and Intradepartmental Eliminations'),
        ('gross_costs','Gross Costs'), ('earned_rev','Earned Revenue'),
        ('recon_outlays','Reconciliation of Net Cost of Operations to Outlays'),
        ('budgetary','Budgetary Resources'), ('service_org','Service Organizations'),
        ('elc','Component Entity-level Controls'),
        ('oversight_dod','DoD-Wide Oversight and Monitoring')],
 # FY2023 has no roster here by design. DODIG-2024-114 states 28 Agency-Wide
 # material weaknesses and refers the roster to an appendix that is not in the
 # released text. A count without its roster is published as a count.
 2024: [('service_org','Service Organizations'), ('elc','Component Entity-Level Controls'),
        ('oversight_dod','DoD-Wide Oversight and Monitoring'), ('leases','Leases'),
        ('inventory','Inventory and Stockpile Materials'),
        ('oms','Operating Materials and Supplies'),
        ('gpppe','General Property, Plant, and Equipment'), ('realprop','Real Property'),
        ('gfp','Government Property in the Possession of Contractors'),
        ('jsf','Joint Strike Fighter Program'),
        ('access','Access Controls'), ('sod','Segregation of Duties'),
        ('interface','Interface Controls'),
        ('fin_systems_it','Financial Management Systems Modernization'),
        ('config_mgmt','Configuration Management'), ('security_mgmt','Security Management'),
        ('begbal','Beginning Balances'), ('unsupported_adj','Unsupported Accounting Adjustments'),
        ('intragov','Intragovernmental Transactions and Intradepartmental Eliminations'),
        ('ap','Accounts Payable'), ('gross_costs','Gross Costs'),
        ('budgetary','Budgetary Resources'), ('earned_rev','Earned Revenue'),
        ('recon_outlays','Reconciliation of Net Cost of Operations to Outlays'),
        ('uot','Universe of Transactions'), ('security_assistance','Security Assistance Accounts'),
        ('fbwt','Fund Balance with Treasury'), ('env','Environmental and Disposal Liabilities')],
 2025: [('fin_systems_it','Financial Management Systems Modernization'),
        ('config_mgmt','Configuration Management'), ('security_mgmt','Security Management'),
        ('access','Access Controls'), ('sod','Segregation of Duties'),
        ('interface','Interface Controls'), ('uot','Universe of Transactions'),
        ('fbwt','Fund Balance with Treasury'), ('inventory','Inventory and Stockpile Materials'),
        ('oms','Operating Materials and Supplies'),
        ('gpppe','General Property, Plant, and Equipment'), ('realprop','Real Property'),
        ('gfp','Government Property in the Possession of Contractors'),
        ('jsf','Joint Strike Fighter Program'), ('ap','Accounts Payable'),
        ('env','Environmental and Disposal Liabilities'), ('leases','Leases'),
        ('unsupported_adj','Unsupported Accounting Adjustments'),
        ('intragov','Intragovernmental Transactions and Intradepartmental Eliminations'),
        ('gross_costs','Gross Costs'), ('earned_rev','Earned Revenue'),
        ('recon_outlays','Reconciliation of Net Cost of Operations to Outlays'),
        ('budgetary','Budgetary Resources'), ('service_org','Service Organizations'),
        ('elc','Component Entity-Level Controls'),
        ('oversight_dod','DoD-Wide Oversight and Monitoring')],
}
ROSTER_CITE = {y: SRC[y][0] for y in ROSTER}
# The FY2024 roster is printed in Part 2, not in the Part 1 report that carries
# the counts, so the roster rows cite Part 2 and the count rows cite Part 1.
ROSTER_CITE[2024] = SRC_2024P2[0]

# Grouping used by the FY2024 report, kept because it is the Department's own
# way of saying which weaknesses it considers one problem.
OBSTACLE = {
  'service_org':'Management responsibility and accountability','elc':'Management responsibility and accountability',
  'oversight_dod':'Management responsibility and accountability','leases':'Management responsibility and accountability',
  'inventory':'Management responsibility and accountability','oms':'Management responsibility and accountability',
  'gpppe':'Management responsibility and accountability','realprop':'Management responsibility and accountability',
  'gfp':'Management responsibility and accountability','jsf':'Management responsibility and accountability',
  'access':'Information technology','sod':'Information technology','interface':'Information technology',
  'fin_systems_it':'Information technology','config_mgmt':'Information technology',
  'security_mgmt':'Information technology','config_security':'Information technology',
  'begbal':'Accounting','unsupported_adj':'Accounting','intragov':'Accounting','ap':'Accounting',
  'gross_costs':'Accounting','budgetary':'Accounting','earned_rev':'Accounting',
  'recon_outlays':'Accounting','uot':'Accounting','security_assistance':'Accounting',
  'fbwt':'Accounting','env':'Accounting','compilation':'Accounting','ar':'Accounting',
  'legal':'Accounting','suspense':'Accounting','mhpi':'Management responsibility and accountability',
  'reporting_entity':'Accounting','component_accounts':'Accounting',
  'oversight_comp':'Management responsibility and accountability',
}
